mversion: '2.1'

services:
  kenyaemr-demo-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-test}
      MYSQL_USER: ${MYSQL_USER:-test}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test}
      TZ: "Africa/Nairobi"
    healthcheck:
      test: "exit 0"

  kenyaemr-demo:
    restart: "always"
    image: tomcat:9-jre8-openjdk
    depends_on:
      - kenyaemr-demo-mysql
    ports:
      - "8500:8443"
      - "8501:8080"
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: kenyaemr-demo-mysql
      DB_USERNAME: ${MYSQL_USER:-test}
      DB_PASSWORD: ${MYSQL_PASSWORD:-test}
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
      TZ: "Africa/Nairobi"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/openmrs/"]
      timeout: 20s