import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/openmrs/spa/login');
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('admin');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Password').fill('Admin123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.locator('label').filter({ hasText: 'Isinya Health Centre' }).locator('span').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByLabel('Add Patient').click();
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('mch');
  await page.getByLabel('Middle Name (optional)').click();
  await page.getByLabel('Middle Name (optional)').fill('test');
  await page.getByLabel('Family Name').click();
  await page.getByLabel('Family Name').fill('oneone');
  await page.locator('fieldset span').nth(2).click();
  await page.getByRole('tab', { name: 'No' }).click();
  await page.getByLabel('Estimated age in years').click();
  await page.getByLabel('Estimated age in years').fill('34');
  await page.getByLabel('Telephone contact').click();
  await page.getByLabel('Telephone contact').fill('0700000000');
  await page.getByLabel('Location', { exact: true }).click();
  await page.getByLabel('Location', { exact: true }).fill('nairobi');
  await page.getByLabel('Sub-location').click();
  await page.getByLabel('Sub-location').fill('subnairobi');
  await page.getByLabel('Village').click();
  await page.getByLabel('Village').fill('vil nairobi');
  await page.getByLabel('Landmark').click();
  await page.getByLabel('Landmark').fill('lan nairobi');
  await page.getByLabel('Marital status').selectOption('1059AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
  await page.getByLabel('Occupation').selectOption('1539AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
  await page.getByLabel('Education').selectOption('1714AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
  await page.getByRole('button', { name: 'Post to registry' }).click();
  await page.getByRole('button', { name: 'Register Patient' }).click();
  await page.getByLabel('Nearest Health Center').fill('health nairobi');
  await page.getByRole('button', { name: 'Register Patient' }).click();
  // // await page.getByLabel('Close snackbar').click();
  // await page.getByLabel('Open menu').click();
  // await page.getByRole('link', { name: 'Care panel' }).click();
  // await page.getByRole('tab', { name: 'Program enrollment' }).click();
  // await page.getByRole('row', { name: 'MCH - Mother Services' }).getByRole('button').click();
  // await page.getByRole('button', { name: 'Start new visit' }).click();
  // await page.locator('label').filter({ hasText: 'Outpatient' }).locator('span').first().click();
  // await page.getByLabel('Select a queue location').selectOption('96a6602c-8527-4cfc-a778-2d8e73998716');
  // await page.getByLabel('Select a service').selectOption('861d37d3-891d-4ef1-8c53-ef64e356a0d4');
  // await page.getByRole('button', { name: 'Start visit' }).click();
  // await page.getByRole('row', { name: 'MCH - Mother Services' }).getByRole('button').click();
  // await page.getByRole('button', { name: 'Close this panel' }).click();
});