name: Deployin_to_stagin_server

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Execute Development Build Script
        run: |
          chmod +x ./staging-build.sh
          echo "n" | ./staging-build.sh

      - name: Compress frontend folder
        run: tar -czvf frontend-${{ github.sha }}.tar.gz frontend/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ github.sha }}.tar.gz
          path: frontend-${{ github.sha }}.tar.gz

      - name: Upload compressed frontend to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CICD2_HOST }}
          username: ${{ secrets.CICD2_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.CICD2_SECRET }}
          source: frontend-${{ github.sha }}.tar.gz
          target: /apps/githubworkflows/OpenMrs3.0_assets/qa

  Activating_the_assets:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CICD2_HOST }}
          username: ${{ secrets.CICD2_USERNAME }}
          key: ${{ secrets.CICD2_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd /apps/githubworkflows/OpenMrs3.0_assets/qa &&
            sudo tar -xzf frontend-${{ github.sha }}.tar.gz
            sudo bash /apps/workflowConfigs/qa-frontend/copy-to-docker.sh
  release:
    runs-on: ubuntu-latest
    needs: Activating_the_assets
    if: github.event_name == 'release'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Run production build script
        run: |
          chmod +x ./prod-build.sh
          ./prod-build.sh

      - name: Compress frontend folder for release
        run: tar -czvf frontend-release-${{ github.sha }}.tar.gz frontend/

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-release-${{ github.sha }}.tar.gz
          path: frontend-release-${{ github.sha }}.tar.gz
